overrides:
  nanoid: ^3.3.18

allowBuilds:
  '@jasikpark/astro-svg-loader': true
  esbuild: true
  sharp: true
  wrangler: true
  workerd: true
onlyBuiltDependencies:
  - '@jasikpark/astro-svg-loader'
  - esbuild
  - sharp
  - workerd
